apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-database-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-database-server
  template:
    metadata:
      labels:
        app: postgres-database-server
    spec:
      containers:
        - name: postgres-database-server
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-database-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-database-secret
                key: postgres-pass
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-database-secret
                key: postgres-db